#!/usr/bin/env bash
# Regenerates src/SoundData.h from Kenney's CC0 "Impact Sounds" pack
# (https://kenney.nl/assets/impact-sounds). The generated header is committed
# so normal builds need neither network nor ffmpeg — rerun this only to
# change which samples are embedded.
#
# Requires: curl, unzip, ffmpeg, xxd.
set -euo pipefail
cd "$(dirname "$0")/.."

PACK_URL="https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip"
RATE=22050   # mono s16le; dull impact sounds don't benefit from 44.1k
OUT=src/SoundData.h

# Sound-material banks (order matches SoundMat in Block.h, minus None) plus
# footsteps. Break and place share a bank: placing plays the same family at
# a higher pitch and lower gain (see Audio.cpp), like the big voxel game.
SOFT_SAMPLES=(impactSoft_heavy_000 impactSoft_heavy_001 impactSoft_heavy_002)
STONE_SAMPLES=(impactMining_000 impactMining_001 impactMining_002)
WOOD_SAMPLES=(impactWood_medium_000 impactWood_medium_001 impactWood_medium_002)
STEP_SAMPLES=(footstep_grass_000 footstep_grass_001 footstep_grass_002)

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
curl -sL "$PACK_URL" -o "$work/pack.zip"
unzip -q "$work/pack.zip" -d "$work/pack"

convert() { # name -> $work/<name>.raw (tail silence trimmed)
    local src
    src=$(find "$work/pack" -name "$1.ogg" | head -1)
    [ -n "$src" ] || { echo "sample $1 not found in pack" >&2; exit 1; }
    ffmpeg -v error -i "$src" -ac 1 -ar $RATE \
        -af "areverse,silenceremove=start_periods=1:start_threshold=-50dB,areverse" \
        -f s16le "$work/$1.raw"
}

{
    echo "// GENERATED by tools/make_sounddata.sh — do not edit by hand."
    echo "//"
    echo "// Sound effects from Kenney's \"Impact Sounds\" pack, CC0 (public"
    echo "// domain): https://kenney.nl/assets/impact-sounds — embedded as raw"
    echo "// PCM so the binary stays asset-file-free, like the font and textures."
    echo "// Format: mono, ${RATE} Hz, signed 16-bit little-endian."
    echo "#pragma once"
    echo
    echo "constexpr int SOUND_DATA_RATE = ${RATE};"
    echo
    for name in "${SOFT_SAMPLES[@]}" "${STONE_SAMPLES[@]}" "${WOOD_SAMPLES[@]}" "${STEP_SAMPLES[@]}"; do
        convert "$name"
        xxd -i -n "snd_${name}" "$work/$name.raw" | sed 's/^unsigned/static const unsigned/'
        echo
    done
    echo "struct EmbeddedSound { const unsigned char* data; unsigned len; };"
    emit_table() {
        local var=$1; shift
        echo "static const EmbeddedSound ${var}[] = {"
        for name in "$@"; do
            echo "    {snd_${name}, snd_${name}_len},"
        done
        echo "};"
    }
    emit_table SND_SOFT "${SOFT_SAMPLES[@]}"
    emit_table SND_STONE "${STONE_SAMPLES[@]}"
    emit_table SND_WOOD "${WOOD_SAMPLES[@]}"
    emit_table SND_STEP "${STEP_SAMPLES[@]}"
    echo
    echo "// Banks 0..2 = SoundMat::{Soft,Stone,Wood} - 1; bank 3 = footsteps."
    echo "struct SoundBankEntry { const EmbeddedSound* variants; int count; };"
    echo "constexpr int SOUND_BANK_COUNT = 4;"
    echo "constexpr int SOUND_BANK_STEP = 3; // footstep bank index"
    echo "static const SoundBankEntry SOUND_BANK[SOUND_BANK_COUNT] = {"
    echo "    {SND_SOFT, ${#SOFT_SAMPLES[@]}},"
    echo "    {SND_STONE, ${#STONE_SAMPLES[@]}},"
    echo "    {SND_WOOD, ${#WOOD_SAMPLES[@]}},"
    echo "    {SND_STEP, ${#STEP_SAMPLES[@]}},"
    echo "};"
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
